import { IGroup } from "../types/group.types";
import { ITransaction } from "../types/transaction.types";

export const ALL_GROUPS: Record<string, IGroup> = {
  // ── JOINED (member) ──────────────────────────────────────────────────────
  "1": {
    id: "1",
    name: "Lagos Tech Circle",
    description: "Monthly savings for tech professionals in Lagos.",
    longDescription:
      "A curated group of tech professionals across Lagos saving together monthly. Members span engineering, product, and design roles at both startups and big tech. Trust and accountability are at the core of this circle.",
    rules: [
      "Contributions must be made before the 5th of every month.",
      "Missed payments attract a 10% penalty on the contribution amount.",
      "Payout recipients must confirm receipt within 48 hours.",
      "Members must give 2 weeks' notice before exiting.",
    ],
    contribution: 50000,
    frequency: "monthly",
    payout_order: "rotational",
    status: "active",
    isPrivate: false,
    membersCount: 8,
    max_members: 10,
    nextDue: "2026-06-05",
    nextPayout: "2026-06-01",
    cycleStartDate: "2026-01-01",
    currentCycle: 5,
    totalCycles: 10,
    totalPaidOut: 2000000,
    trustScore: 98,
    adminName: "Emeka Obi",
    adminInitials: "EO",
    spotsLeft: 2,
    inviteCode: "LTC-2026-X7",
    myMemberId: "m3",
    members: [
      { id: "m1", name: "Emeka Obi",     initials: "EO", role: "admin",  status: "active",   turnPosition: 1, hasPaidThisCycle: true,  totalContributed: 250000, hasReceived: true  },
      { id: "m2", name: "Adaeze Nwosu",  initials: "AN", role: "member", status: "active",   turnPosition: 2, hasPaidThisCycle: true,  totalContributed: 250000, hasReceived: true  },
      { id: "m3", name: "You",           initials: "ME", role: "member", status: "active",   turnPosition: 3, hasPaidThisCycle: true,  totalContributed: 200000, hasReceived: false },
      { id: "m4", name: "Chidi Eze",     initials: "CE", role: "member", status: "active",   turnPosition: 4, hasPaidThisCycle: false, totalContributed: 150000, hasReceived: false },
      { id: "m5", name: "Fatima Bello",  initials: "FB", role: "member", status: "active",   turnPosition: 5, hasPaidThisCycle: true,  totalContributed: 200000, hasReceived: false },
      { id: "m6", name: "Tunde Bakare",  initials: "TB", role: "member", status: "defaulted",turnPosition: 6, hasPaidThisCycle: false, totalContributed: 100000, hasReceived: false },
      { id: "m7", name: "Ngozi Adeyemi", initials: "NA", role: "member", status: "active",   turnPosition: 7, hasPaidThisCycle: true,  totalContributed: 200000, hasReceived: false },
      { id: "m8", name: "Seun Falola",   initials: "SF", role: "member", status: "active",   turnPosition: 8, hasPaidThisCycle: true,  totalContributed: 200000, hasReceived: false },
    ],
  },

  "2": {
    id: "2",
    name: "Abuja Women Save",
    description: "Empowering women through collective savings. Weekly contributions for big dreams.",
    longDescription:
      "A women-led savings circle based in Abuja. Members contribute weekly and payouts are determined by random draw at the start of each cycle. The admin verifies all members and ensures complete transparency.",
    rules: [
      "Open to women only.",
      "Contributions are due every Friday before 6pm.",
      "Payout draw is held every new cycle at a virtual meeting.",
      "Members may invite other women via the invite code only.",
    ],
    contribution: 10000,
    frequency: "weekly",
    payout_order: "random",
    status: "active",
    isPrivate: true,
    membersCount: 14,
    max_members: 20,
    nextDue: "2026-05-23",
    nextPayout: "2026-05-18",
    cycleStartDate: "2026-04-01",
    currentCycle: 7,
    totalCycles: 20,
    totalPaidOut: 700000,
    trustScore: 87,
    adminName: "Mama Chidinma",
    adminInitials: "MC",
    spotsLeft: 6,
    inviteCode: "AWS-FCT-99",
    myMemberId: "m1",
    members: [
      { id: "m1", name: "You (Admin)",    initials: "ME", role: "admin",  status: "active",  turnPosition: 1, hasPaidThisCycle: true,  totalContributed: 70000, hasReceived: false },
      { id: "m2", name: "Amaka Okonkwo", initials: "AO", role: "member", status: "active",  turnPosition: 2, hasPaidThisCycle: true,  totalContributed: 70000, hasReceived: true  },
      { id: "m3", name: "Zainab Musa",   initials: "ZM", role: "member", status: "active",  turnPosition: 3, hasPaidThisCycle: false, totalContributed: 60000, hasReceived: false },
      { id: "m4", name: "Grace Eze",     initials: "GE", role: "member", status: "active",  turnPosition: 4, hasPaidThisCycle: true,  totalContributed: 70000, hasReceived: true  },
      { id: "m5", name: "Halima Ibrahim",initials: "HI", role: "member", status: "pending", turnPosition: 5, hasPaidThisCycle: false, totalContributed: 50000, hasReceived: false },
    ],
  },

  // ── DISCOVER (non-member) ────────────────────────────────────────────────
  "d1": {
    id: "d1",
    name: "Lagos Tech Professionals",
    description: "A tight-knit savings circle for tech workers in Lagos.",
    longDescription:
      "Members include engineers, designers, and PMs from top companies across Lagos. Monthly contributions with rotational payouts, verified identities, and zero tolerance for defaults. One of the highest-rated circles on the platform.",
    rules: [
      "Proof of tech employment required on signup.",
      "Contributions due on the 1st of every month.",
      "Two consecutive missed payments result in automatic removal.",
      "New members must be vouched for by an existing member.",
    ],
    contribution: 50000,
    frequency: "monthly",
    payout_order: "rotational",
    status: "active",
    isPrivate: false,
    membersCount: 7,
    max_members: 10,
    nextDue: "2026-06-01",
    nextPayout: "2026-06-01",
    cycleStartDate: "2026-01-01",
    currentCycle: 5,
    totalCycles: 10,
    totalPaidOut: 3500000,
    trustScore: 98,
    adminName: "Emeka Obi",
    adminInitials: "EO",
    spotsLeft: 3,
    myMemberId: null,
    members: [
      { id: "m1", name: "Emeka Obi",  initials: "EO", role: "admin",  status: "active", turnPosition: 1, hasPaidThisCycle: true,  totalContributed: 250000, hasReceived: true  },
      { id: "m2", name: "Adaeze N.", initials: "AN", role: "member", status: "active", turnPosition: 2, hasPaidThisCycle: true,  totalContributed: 250000, hasReceived: true  },
      { id: "m3", name: "Chidi E.",  initials: "CE", role: "member", status: "active", turnPosition: 3, hasPaidThisCycle: true,  totalContributed: 200000, hasReceived: false },
      { id: "m4", name: "Fatima B.", initials: "FB", role: "member", status: "active", turnPosition: 4, hasPaidThisCycle: true,  totalContributed: 200000, hasReceived: false },
      { id: "m5", name: "Tunde B.",  initials: "TB", role: "member", status: "active", turnPosition: 5, hasPaidThisCycle: true,  totalContributed: 200000, hasReceived: false },
      { id: "m6", name: "Ngozi A.",  initials: "NA", role: "member", status: "active", turnPosition: 6, hasPaidThisCycle: false, totalContributed: 150000, hasReceived: false },
      { id: "m7", name: "Seun F.",   initials: "SF", role: "member", status: "active", turnPosition: 7, hasPaidThisCycle: true,  totalContributed: 200000, hasReceived: false },
    ],
  },

  "d8": {
    id: "d8",
    name: "Real Estate Investors Circle",
    description: "Serious investors pooling capital for property down-payments.",
    longDescription:
      "High-contribution circle for serious property investors. Payouts are allocated via bidding — members bid for early payout slots by offering a premium to the pool. Background verification is mandatory. All members are confirmed property investors.",
    rules: [
      "Background check and identity verification mandatory.",
      "Minimum 6-month commitment; exits attract a 15% penalty.",
      "Bidding opens on the 25th of each month.",
      "Winning bidder must confirm property purpose within 30 days.",
    ],
    contribution: 500000,
    frequency: "monthly",
    payout_order: "bidding",
    status: "active",
    isPrivate: false,
    membersCount: 4,
    max_members: 6,
    nextDue: "2026-06-01",
    nextPayout: "2026-06-01",
    cycleStartDate: "2026-02-01",
    currentCycle: 4,
    totalCycles: 6,
    totalPaidOut: 24000000,
    trustScore: 100,
    adminName: "Mr. Rotimi Adeyemo",
    adminInitials: "RA",
    spotsLeft: 2,
    myMemberId: null,
    members: [
      { id: "m1", name: "Rotimi A.",    initials: "RA", role: "admin",  status: "active", turnPosition: 1, hasPaidThisCycle: true,  totalContributed: 2000000, hasReceived: true  },
      { id: "m2", name: "Kunle O.",     initials: "KO", role: "member", status: "active", turnPosition: 2, hasPaidThisCycle: true,  totalContributed: 2000000, hasReceived: true  },
      { id: "m3", name: "Yetunde A.",   initials: "YA", role: "member", status: "active", turnPosition: 3, hasPaidThisCycle: true,  totalContributed: 2000000, hasReceived: false },
      { id: "m4", name: "Babatunde F.", initials: "BF", role: "member", status: "active", turnPosition: 4, hasPaidThisCycle: false, totalContributed: 1500000, hasReceived: false },
    ],
  },
};

export const SAMPLE_TRANSACTIONS: ITransaction[] = [
  { id: "t1", type: "contribution", amount: 50000, date: "2026-05-01", status: "success", description: "Cycle 5 contribution" },
  { id: "t2", type: "contribution", amount: 50000, date: "2026-04-01", status: "success", description: "Cycle 4 contribution" },
  { id: "t3", type: "contribution", amount: 50000, date: "2026-03-01", status: "success", description: "Cycle 3 contribution" },
  { id: "t4", type: "contribution", amount: 50000, date: "2026-02-01", status: "success", description: "Cycle 2 contribution" },
  { id: "t5", type: "contribution", amount: 50000, date: "2026-01-01", status: "success", description: "Cycle 1 contribution" },
];